### ISSUE TITLE
W3C vendor-neutral important wording

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wcag-act-rules#100]
From https://github.com/w3c/wcag-act-rules/pull/99#discussion_r867824209
> I do want to explicitly say that ACT rules lets us compare implementations.

We need to be very thoughtful and careful about wording here. W3C should not be perceived as comparing vendor tools. We need to provide the information and wording in a way that limits confusion and potential problems with this work.

The words 'compare' and 'score' send up flags for me. Please think carefully about how we can present the info clearly and comfortably. (I don't think we need to involve W3C legal or Judy, yet might.)

**Comment by WilcoFiers** [comment]
Noted, but let's have the conversation on PR #95. Lets reserve issues for things that are live, and put comments about PRs on that PR.
