### ISSUE TITLE
Non descriptive label for the navigation bar

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wcag-act-rules#149]
This is for @WilcoFiers @shawna-slh  and @SteveALee to review and comment.

Currently, the navigation bar for the ACT rules pages is labelled as "false navigation".

I think this is coming from the standalone template key:
```yaml
type_of_guidance: false
```

that we have on the ACT rules frontmatter.

What would be the consequences of adding
```yaml
type_of_guidance: "ACT Rules"
```

**Comment by SteveALee** [comment]
That's probably a bug. type_of_guidance probably only affects the subtitle on pages and false hides it.

I assume you are talking about aria-label?

**Comment by daniel-montalvo** [comment]
Thanks @SteveALee 

Yes, I am talking about aria-label

AS per standalone resource template:

```html
          <nav class="nav standalone-resource-pager" aria-label="{{page.type_of_guidance}}">
```

**Comment by daniel-montalvo** [comment]
Thanks much @SteveALee 

+1 to 

when `type_of_guidance: false` then
no aria-label contents

Not sure why @WilcoFiers thought using `type_of_guidance: "ACT Rules"` was not good, probably because the text would show up.

Would using `type_of_guidance: ""` on our end fix it?

I am looking here for the easiest, less time-consuming workaround for us all :-)

**Comment by SteveALee** [comment]
@daniel-montalvo It's worth a go. I'm pretty sure that an empty string is not the same as false
