### ISSUE TITLE
Change "test cases" to "examples"

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wcag-act-rules#173]
In ACT Rules Format and Rules themselves we use "test cases". While being the most accurate term, it poses some difficulty to understand for some. We've found ourselves explaining these as "examples" in outreach efforts lately.

From [15 December ACT meeting](https://www.w3.org/2022/12/15-wcag-act-minutes.html#item06) it seems that the group is keen to continue using "test cases" as that is the technical term, but it was not clear how to help those that have difficulty with the term better understand its meaning.

This issue is to collect further feedback on the topic.

**Comment by ChrisLoiselle** [comment]
I prefer test case in that you are using an use case and testing against it.  @daniel-montalvo

**Comment by WilcoFiers** [comment]
Closing, the task force decided to continue with the terms as is.
