### ISSUE TITLE
Set up redirects to proposed rules

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act-rules#216]
We currently have 70 proposed rules, and 22 approved rules. For the approved rules we keep two versions, a draft and an approved version. For the proposed rules we just have the draft. For the proposed rules I would like to have a redirect set up that goes from from where the approved version would be to the proposed version.

For example, this is an approved rule and its draft version:
- [WAI/standards-guidelines/act/rules/73f2c2/](https://www.w3.org/WAI/standards-guidelines/act/rules/73f2c2/)
- [WAI/standards-guidelines/act/rules/73f2c2/proposed](https://www.w3.org/WAI/standards-guidelines/act/rules/73f2c2/proposed)

And here's one that isn't approved yet:
- [WAI/standards-guidelines/act/rules/5f99a7/](https://www.w3.org/WAI/standards-guidelines/act/rules/5f99a7/) This one is broken, but should redirect:
- [WAI/standards-guidelines/act/rules/5f99a7/proposed/https://www.w3.org/WAI/standards-guidelines/act/rules/5f99a7/proposed/](https://www.w3.org/WAI/standards-guidelines/act/rules/5f99a7/proposed/https://www.w3.org/WAI/standards-guidelines/act/rules/5f99a7/proposed/)

I heard from @shawna-slh that we can set these redirects up manually. As a one-off that's fine. It's 70 redirects but that's doable. The issue is in how to maintain such a list though. We have proposed rules getting approved with some regularity, and then from time to time we have new rules as well. It would be easy to overlook redirects if we have to do them by hand, so ideally we'd have some solution for doing this automatically.

I can easily generate a list of rules or URLs that require a redirect and put them somewhere. I could also use meta refresh to do this myself, but I imagine that's not the preferred solution. I've tested that out here though, and it does work (at least, on Netlify it does): https://github.com/w3c/wcag-act-rules/pull/200/files#diff-69b12f7fd66b367320823fa2fedfb7e3a5f91b8401d009c76f9fb46a57b31a20

I would like to know what the best solution for this would be. I don't really want to maintain this by hand, but if that's the only option it's not impossible.

**Comment by shawna-slh** [comment]
As WAI site maintainer, I'm OK with these redirects as Wilco and Daniel find useful.

I leave it to Daniel to work with SysTeam on the first batch of redirects, and potentially a system to update redirects.
