### ISSUE TITLE
A link ends in 404

### ISSUE THREAD

**Issue by otaria-o** [w3c/wcag-act-rules#247]
this is the page: https://www.w3.org/WAI/standards-guidelines/act/rules/about/
the link "test tools and metodologies" ends in 404 document not found: https://www.w3.org/WAI/standards-guidelines/act/rules/implementations/

the right address may be https://www.w3.org/WAI/standards-guidelines/act/implementations/ instead.

**Comment by WilcoFiers** [comment]
Thanks for reporting this. I fixed the link, it should be sorted the next time the site gets released (probably Tuesday)
